config/routes.rb
Rails.application.routes.draw do

  resources :products do
    post 'take', on: :member
  end

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    load_product
  end

  def new
    @product = Product.new
  end

  def edit
    load_product
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    load_product

    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def take
    load_product

    @product.decrement!(:quantity)

    render text: @product.quantity
  end

  private

  def load_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Inventory > <%= "#{controller.controller_name}: #{controller.action_name}".titlecase %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<fieldset>
  <%= f.label :name %>
  <%= f.text_field :name %>
</fieldset>
<fieldset>
  <%= f.label :quantity %>
  <%= f.text_field :quantity, :size => 5 %>
</fieldset>
<fieldset>
  <%= f.label :description %>
  <%= f.text_area :description %>
</fieldset>

app/views/products/_product.html.erb
<li>
  <div class="table">
    <div class="table-cell">
      <%= link_to product.name, product_path(product) %>
    </div>
    <div class="table-cell">
      <span class="quantity">
        <%= product.quantity %>
      </span>
      <%= link_to raw('&ndash;'), take_product_path(product), 'data-decrement-quantity' => '', class: 'button round small' %>
    </div>
  </div>
  <% if product.description.present? %>
    <%= product.description %>
    <br />
  <% end %>
  <%= link_to 'Edit', edit_product_path(product) %>
</li>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
  <%= render 'form', f: f %>
  <p>
    <%= f.submit 'Save Changes' %>
    <%= link_to 'Cancel', product_path(@product), class: 'button cancel' %>
  </p>
<% end %>

app/views/products/index.html.erb
<p>
  <%= link_to 'New Product', new_product_path, class: 'button new' %>
</p>

<ul id="products" class="list">
  <%= render @products %>
</ul>

<script>
  $(document).ready(function(){
    products.init();
  });
</script>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
  <%= render 'form', f: f %>
  <p>
    <%= f.submit 'Save Product' %>
    <%= link_to 'Cancel', products_path, class: 'button cancel' %>
  </p>
<% end %>

app/views/products/show.html.erb
<p>
  <%= link_to 'Back to products', products_path, class: 'small' %>
</p>
<h1>
  <%= @product.name %>
</h1>
<p>
  <%= "Quantity: #{@product.quantity}" %>
</p>
<p>
  <%= @product.description %>
</p>
<p>
  <%= link_to 'Edit', edit_product_path(@product), class: 'button' %>
</p>